# Cloudflare Pages 환경 설정 파일
name = "smp-curve-studio"
pages_build_output_dir = "dist"

# D1 Database 바인딩
[[d1_databases]]
binding = "DB"
database_name = "smp-studio-db"
database_id = "5011362c-7929-466b-a424-7f4bde29aec5"

# R2 Storage 바인딩
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "smp-studio-media"
preview_bucket_name = "smp-studio-media-preview"
